name: basisbase
description: >-
  A Dart database and library for atom-centered basis functions used in
  computational and quantum chemistry.
version: 1.0.0
repository: https://github.com/bingao/basisbase

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
